import numpy as np
row_vec = np.array([7,2,9])
print(row_vec)
print(row_vec.shape)
print(row_vec.reshape(1,3))
col_vec = np.array([3,1,7,4])
print(col_vec.reshape(4,1))
mat = np.array([[2,0], [5,1], [7,-3]])
print(mat)
print(mat.shape)
M = np.arange(100).reshape(10,10)
print(M)